# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ros_qt2_new.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1203, 707)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/c1s/c1s.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(930, 20, 251, 641))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setMaximumSize(QtCore.QSize(249, 292))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_26.addWidget(self.label_7)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setSpacing(2)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_101 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_101.setFont(font)
        self.label_101.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_101.setAlignment(QtCore.Qt.AlignCenter)
        self.label_101.setObjectName("label_101")
        self.verticalLayout_7.addWidget(self.label_101)
        self.label_97 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_97.setFont(font)
        self.label_97.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_97.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_97.setAlignment(QtCore.Qt.AlignCenter)
        self.label_97.setObjectName("label_97")
        self.verticalLayout_7.addWidget(self.label_97)
        self.verticalLayout_24.addLayout(self.verticalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_90 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_90.setFont(font)
        self.label_90.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_8.addWidget(self.label_90)
        self.label_92 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_92.setFont(font)
        self.label_92.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.verticalLayout_8.addWidget(self.label_92)
        self.horizontalLayout_10.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_82 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_82.setFont(font)
        self.label_82.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.verticalLayout_9.addWidget(self.label_82)
        self.label_83 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_83.setFont(font)
        self.label_83.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.verticalLayout_9.addWidget(self.label_83)
        self.horizontalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_85 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_85.setFont(font)
        self.label_85.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_10.addWidget(self.label_85)
        self.label_84 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_84.setFont(font)
        self.label_84.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_10.addWidget(self.label_84)
        self.horizontalLayout_10.addLayout(self.verticalLayout_10)
        self.verticalLayout_24.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_80 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_80.setFont(font)
        self.label_80.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.verticalLayout_11.addWidget(self.label_80)
        self.label_81 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_81.setFont(font)
        self.label_81.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.verticalLayout_11.addWidget(self.label_81)
        self.horizontalLayout_9.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_78 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_78.setFont(font)
        self.label_78.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.verticalLayout_12.addWidget(self.label_78)
        self.label_79 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_79.setFont(font)
        self.label_79.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.verticalLayout_12.addWidget(self.label_79)
        self.horizontalLayout_9.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_76 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_76.setFont(font)
        self.label_76.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.verticalLayout_13.addWidget(self.label_76)
        self.label_77 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_77.setFont(font)
        self.label_77.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.verticalLayout_13.addWidget(self.label_77)
        self.horizontalLayout_9.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_73 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.verticalLayout_14.addWidget(self.label_73)
        self.label_72 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_14.addWidget(self.label_72)
        self.horizontalLayout_9.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_74 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_74.setFont(font)
        self.label_74.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName("label_74")
        self.verticalLayout_15.addWidget(self.label_74)
        self.label_75 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_75.setFont(font)
        self.label_75.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_15.addWidget(self.label_75)
        self.horizontalLayout_9.addLayout(self.verticalLayout_15)
        self.verticalLayout_24.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_95 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_95.setFont(font)
        self.label_95.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_95.setAlignment(QtCore.Qt.AlignCenter)
        self.label_95.setObjectName("label_95")
        self.verticalLayout_19.addWidget(self.label_95)
        self.label_94 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_94.setFont(font)
        self.label_94.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_19.addWidget(self.label_94)
        self.horizontalLayout_8.addLayout(self.verticalLayout_19)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_96 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_96.setFont(font)
        self.label_96.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_96.setAlignment(QtCore.Qt.AlignCenter)
        self.label_96.setObjectName("label_96")
        self.verticalLayout_16.addWidget(self.label_96)
        self.label_98 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_98.setFont(font)
        self.label_98.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName("label_98")
        self.verticalLayout_16.addWidget(self.label_98)
        self.horizontalLayout_8.addLayout(self.verticalLayout_16)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_89 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_89.setFont(font)
        self.label_89.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName("label_89")
        self.verticalLayout_20.addWidget(self.label_89)
        self.label_88 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_88.setFont(font)
        self.label_88.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName("label_88")
        self.verticalLayout_20.addWidget(self.label_88)
        self.horizontalLayout_8.addLayout(self.verticalLayout_20)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_91 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_91.setFont(font)
        self.label_91.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.verticalLayout_17.addWidget(self.label_91)
        self.label_99 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_99.setFont(font)
        self.label_99.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName("label_99")
        self.verticalLayout_17.addWidget(self.label_99)
        self.horizontalLayout_8.addLayout(self.verticalLayout_17)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_87 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_87.setFont(font)
        self.label_87.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_21.addWidget(self.label_87)
        self.label_86 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_86.setFont(font)
        self.label_86.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_21.addWidget(self.label_86)
        self.horizontalLayout_8.addLayout(self.verticalLayout_21)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_93 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_93.setFont(font)
        self.label_93.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.verticalLayout_18.addWidget(self.label_93)
        self.label_100 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_100.setFont(font)
        self.label_100.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_100.setAlignment(QtCore.Qt.AlignCenter)
        self.label_100.setObjectName("label_100")
        self.verticalLayout_18.addWidget(self.label_100)
        self.horizontalLayout_8.addLayout(self.verticalLayout_18)
        self.verticalLayout_24.addLayout(self.horizontalLayout_8)
        self.label_116 = QtWidgets.QLabel(self.layoutWidget)
        self.label_116.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_116.setFont(font)
        self.label_116.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_116.setObjectName("label_116")
        self.verticalLayout_24.addWidget(self.label_116)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_110 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_110.setFont(font)
        self.label_110.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_110.setAlignment(QtCore.Qt.AlignCenter)
        self.label_110.setObjectName("label_110")
        self.verticalLayout_5.addWidget(self.label_110)
        self.label_111 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_111.setFont(font)
        self.label_111.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_111.setAlignment(QtCore.Qt.AlignCenter)
        self.label_111.setObjectName("label_111")
        self.verticalLayout_5.addWidget(self.label_111)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_113 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_113.setFont(font)
        self.label_113.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_113.setAlignment(QtCore.Qt.AlignCenter)
        self.label_113.setObjectName("label_113")
        self.verticalLayout_6.addWidget(self.label_113)
        self.label_112 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_112.setFont(font)
        self.label_112.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_112.setAlignment(QtCore.Qt.AlignCenter)
        self.label_112.setObjectName("label_112")
        self.verticalLayout_6.addWidget(self.label_112)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.verticalLayout_24.addLayout(self.horizontalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_115 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_115.setFont(font)
        self.label_115.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_115.setAlignment(QtCore.Qt.AlignCenter)
        self.label_115.setObjectName("label_115")
        self.verticalLayout_4.addWidget(self.label_115)
        self.label_114 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_114.setFont(font)
        self.label_114.setStyleSheet("color:rgb(85, 85, 255)")
        self.label_114.setAlignment(QtCore.Qt.AlignCenter)
        self.label_114.setObjectName("label_114")
        self.verticalLayout_4.addWidget(self.label_114)
        self.verticalLayout_24.addLayout(self.verticalLayout_4)
        self.verticalLayout_26.addLayout(self.verticalLayout_24)
        self.verticalLayout_26.setStretch(0, 6)
        self.verticalLayout_26.setStretch(1, 7)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(11, 1, 875, 41))
        self.groupBox.setMinimumSize(QtCore.QSize(871, 41))
        self.groupBox.setMaximumSize(QtCore.QSize(913, 60))
        self.groupBox.setObjectName("groupBox")
        self.label_71 = QtWidgets.QLabel(self.groupBox)
        self.label_71.setGeometry(QtCore.QRect(449, 17, 81, 20))
        self.label_71.setObjectName("label_71")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(540, 16, 101, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_117 = QtWidgets.QLabel(self.groupBox)
        self.label_117.setGeometry(QtCore.QRect(660, 17, 111, 20))
        self.label_117.setObjectName("label_117")
        self.label_118 = QtWidgets.QLabel(self.groupBox)
        self.label_118.setGeometry(QtCore.QRect(787, 19, 91, 16))
        self.label_118.setObjectName("label_118")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_52.setGeometry(QtCore.QRect(71, 14, 181, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_52.setFont(font)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.label_42 = QtWidgets.QLabel(self.groupBox)
        self.label_42.setGeometry(QtCore.QRect(11, 20, 61, 16))
        self.label_42.setObjectName("label_42")
        self.pushButton_open_close = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_open_close.setGeometry(QtCore.QRect(280, 13, 101, 25))
        self.pushButton_open_close.setObjectName("pushButton_open_close")
        self.tabWidget_all = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_all.setGeometry(QtCore.QRect(11, 48, 911, 631))
        self.tabWidget_all.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget_all.setMaximumSize(QtCore.QSize(1019, 645))
        self.tabWidget_all.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_all.setObjectName("tabWidget_all")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-10, 50, 771, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_ult_check = QtWidgets.QGroupBox(self.tab)
        self.groupBox_ult_check.setGeometry(QtCore.QRect(10, 0, 751, 41))
        self.groupBox_ult_check.setObjectName("groupBox_ult_check")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_ult_check)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 731, 20))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout.addWidget(self.checkBox_8)
        self.groupBox_gyro_data = QtWidgets.QGroupBox(self.tab)
        self.groupBox_gyro_data.setGeometry(QtCore.QRect(910, 510, 16, 16))
        self.groupBox_gyro_data.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_gyro_data.setMaximumSize(QtCore.QSize(16, 16))
        self.groupBox_gyro_data.setObjectName("groupBox_gyro_data")
        self.label_8 = QtWidgets.QLabel(self.groupBox_gyro_data)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 54, 12))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_gyro_data)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 54, 12))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_gyro_data)
        self.label_10.setGeometry(QtCore.QRect(10, 120, 54, 12))
        self.label_10.setObjectName("label_10")
        self.pushButton_13 = QtWidgets.QPushButton(self.groupBox_gyro_data)
        self.pushButton_13.setGeometry(QtCore.QRect(880, 100, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.layoutWidget_9 = QtWidgets.QWidget(self.groupBox_gyro_data)
        self.layoutWidget_9.setGeometry(QtCore.QRect(60, 30, 811, 41))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.u1_9 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.u1_9.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.u1_9.setContentsMargins(0, 0, 0, 0)
        self.u1_9.setSpacing(6)
        self.u1_9.setObjectName("u1_9")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_12.setReadOnly(True)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.u1_9.addWidget(self.lineEdit_12)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_13.setReadOnly(True)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.u1_9.addWidget(self.lineEdit_13)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_14.setReadOnly(True)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.u1_9.addWidget(self.lineEdit_14)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_15.setReadOnly(True)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.u1_9.addWidget(self.lineEdit_15)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_16.setReadOnly(True)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.u1_9.addWidget(self.lineEdit_16)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_17.setReadOnly(True)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.u1_9.addWidget(self.lineEdit_17)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_18.setReadOnly(True)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.u1_9.addWidget(self.lineEdit_18)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_25.setReadOnly(True)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.u1_9.addWidget(self.lineEdit_25)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_26.setReadOnly(True)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.u1_9.addWidget(self.lineEdit_26)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_29.setReadOnly(True)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.u1_9.addWidget(self.lineEdit_29)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_30.setReadOnly(True)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.u1_9.addWidget(self.lineEdit_30)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_31.setReadOnly(True)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.u1_9.addWidget(self.lineEdit_31)
        self.layoutWidget_11 = QtWidgets.QWidget(self.groupBox_gyro_data)
        self.layoutWidget_11.setGeometry(QtCore.QRect(60, 70, 811, 41))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.u1_10 = QtWidgets.QHBoxLayout(self.layoutWidget_11)
        self.u1_10.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.u1_10.setContentsMargins(0, 0, 0, 0)
        self.u1_10.setSpacing(6)
        self.u1_10.setObjectName("u1_10")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget_11)
        self.lineEdit_22.setReadOnly(True)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.u1_10.addWidget(self.lineEdit_22)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget_11)
        self.lineEdit_23.setReadOnly(True)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.u1_10.addWidget(self.lineEdit_23)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget_11)
        self.lineEdit_24.setReadOnly(True)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.u1_10.addWidget(self.lineEdit_24)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.layoutWidget_11)
        self.lineEdit_27.setReadOnly(True)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.u1_10.addWidget(self.lineEdit_27)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.layoutWidget_11)
        self.lineEdit_32.setReadOnly(True)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.u1_10.addWidget(self.lineEdit_32)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.layoutWidget_11)
        self.lineEdit_33.setReadOnly(True)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.u1_10.addWidget(self.lineEdit_33)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.layoutWidget_11)
        self.lineEdit_53.setReadOnly(True)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.u1_10.addWidget(self.lineEdit_53)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.layoutWidget_11)
        self.lineEdit_60.setReadOnly(True)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.u1_10.addWidget(self.lineEdit_60)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.layoutWidget_11)
        self.lineEdit_61.setReadOnly(True)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.u1_10.addWidget(self.lineEdit_61)
        self.lineEdit_74 = QtWidgets.QLineEdit(self.layoutWidget_11)
        self.lineEdit_74.setReadOnly(True)
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.u1_10.addWidget(self.lineEdit_74)
        self.lineEdit_83 = QtWidgets.QLineEdit(self.layoutWidget_11)
        self.lineEdit_83.setReadOnly(True)
        self.lineEdit_83.setObjectName("lineEdit_83")
        self.u1_10.addWidget(self.lineEdit_83)
        self.lineEdit_84 = QtWidgets.QLineEdit(self.layoutWidget_11)
        self.lineEdit_84.setReadOnly(True)
        self.lineEdit_84.setObjectName("lineEdit_84")
        self.u1_10.addWidget(self.lineEdit_84)
        self.layoutWidget_12 = QtWidgets.QWidget(self.groupBox_gyro_data)
        self.layoutWidget_12.setGeometry(QtCore.QRect(60, 110, 811, 41))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.u1_11 = QtWidgets.QHBoxLayout(self.layoutWidget_12)
        self.u1_11.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.u1_11.setContentsMargins(0, 0, 0, 0)
        self.u1_11.setSpacing(6)
        self.u1_11.setObjectName("u1_11")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineEdit_28.setReadOnly(True)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.u1_11.addWidget(self.lineEdit_28)
        self.lineEdit_75 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineEdit_75.setReadOnly(True)
        self.lineEdit_75.setObjectName("lineEdit_75")
        self.u1_11.addWidget(self.lineEdit_75)
        self.lineEdit_76 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineEdit_76.setReadOnly(True)
        self.lineEdit_76.setObjectName("lineEdit_76")
        self.u1_11.addWidget(self.lineEdit_76)
        self.lineEdit_77 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineEdit_77.setReadOnly(True)
        self.lineEdit_77.setObjectName("lineEdit_77")
        self.u1_11.addWidget(self.lineEdit_77)
        self.lineEdit_78 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineEdit_78.setReadOnly(True)
        self.lineEdit_78.setObjectName("lineEdit_78")
        self.u1_11.addWidget(self.lineEdit_78)
        self.lineEdit_79 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineEdit_79.setReadOnly(True)
        self.lineEdit_79.setObjectName("lineEdit_79")
        self.u1_11.addWidget(self.lineEdit_79)
        self.lineEdit_80 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineEdit_80.setReadOnly(True)
        self.lineEdit_80.setObjectName("lineEdit_80")
        self.u1_11.addWidget(self.lineEdit_80)
        self.lineEdit_81 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineEdit_81.setReadOnly(True)
        self.lineEdit_81.setObjectName("lineEdit_81")
        self.u1_11.addWidget(self.lineEdit_81)
        self.lineEdit_82 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineEdit_82.setReadOnly(True)
        self.lineEdit_82.setObjectName("lineEdit_82")
        self.u1_11.addWidget(self.lineEdit_82)
        self.lineEdit_85 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineEdit_85.setReadOnly(True)
        self.lineEdit_85.setObjectName("lineEdit_85")
        self.u1_11.addWidget(self.lineEdit_85)
        self.lineEdit_86 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineEdit_86.setReadOnly(True)
        self.lineEdit_86.setObjectName("lineEdit_86")
        self.u1_11.addWidget(self.lineEdit_86)
        self.lineEdit_87 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineEdit_87.setReadOnly(True)
        self.lineEdit_87.setObjectName("lineEdit_87")
        self.u1_11.addWidget(self.lineEdit_87)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_gyro_data)
        self.layoutWidget2.setGeometry(QtCore.QRect(60, 10, 811, 16))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_2.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_2.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_2.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_2.addWidget(self.label_50)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_2.addWidget(self.label_51)
        self.label_52 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_2.addWidget(self.label_52)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_2.addWidget(self.label_53)
        self.label_55 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_2.addWidget(self.label_55)
        self.label_54 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_2.addWidget(self.label_54)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(780, 20, 121, 441))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.checkBox_15 = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.checkBox_15.setObjectName("checkBox_15")
        self.verticalLayout_37.addWidget(self.checkBox_15)
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.verticalLayout_52 = QtWidgets.QVBoxLayout()
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.toolBox = QtWidgets.QToolBox(self.layoutWidget_2)
        self.toolBox.setEnabled(True)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 115, 118))
        self.page.setObjectName("page")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 115, 118))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 115, 118))
        self.page_3.setObjectName("page_3")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 115, 118))
        self.page_4.setObjectName("page_4")
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 115, 118))
        self.page_5.setObjectName("page_5")
        self.toolBox.addItem(self.page_5, "")
        self.verticalLayout_52.addWidget(self.toolBox)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_52.addWidget(self.pushButton_11)
        self.verticalLayout_52.setStretch(1, 3)
        self.verticalLayout_53.addLayout(self.verticalLayout_52)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_53.addItem(spacerItem)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_36.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_44.setAlignment(QtCore.Qt.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_36.addWidget(self.label_44)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_36.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_36.addWidget(self.label_46)
        self.verticalLayout_53.addLayout(self.verticalLayout_36)
        self.verticalLayout_53.setStretch(0, 5)
        self.verticalLayout_53.setStretch(1, 1)
        self.verticalLayout_53.setStretch(2, 1)
        self.verticalLayout_37.addLayout(self.verticalLayout_53)
        self.groupBox_ult_data = QtWidgets.QGroupBox(self.tab)
        self.groupBox_ult_data.setGeometry(QtCore.QRect(10, 480, 891, 121))
        self.groupBox_ult_data.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_ult_data.setObjectName("groupBox_ult_data")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_ult_data)
        self.pushButton_4.setGeometry(QtCore.QRect(810, 62, 75, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_ult_data)
        self.layoutWidget3.setGeometry(QtCore.QRect(60, 30, 731, 80))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.u1 = QtWidgets.QHBoxLayout()
        self.u1.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.u1.setSpacing(6)
        self.u1.setObjectName("u1")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.u1.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.u1.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.u1.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.u1.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.u1.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.u1.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.u1.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.u1.addWidget(self.lineEdit_8)
        self.verticalLayout_40.addLayout(self.u1)
        self.u1_2 = QtWidgets.QHBoxLayout()
        self.u1_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.u1_2.setSpacing(6)
        self.u1_2.setObjectName("u1_2")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.u1_2.addWidget(self.lineEdit_9)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_19.setReadOnly(True)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.u1_2.addWidget(self.lineEdit_19)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_20.setReadOnly(True)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.u1_2.addWidget(self.lineEdit_20)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_21.setReadOnly(True)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.u1_2.addWidget(self.lineEdit_21)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_34.setReadOnly(True)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.u1_2.addWidget(self.lineEdit_34)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_35.setReadOnly(True)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.u1_2.addWidget(self.lineEdit_35)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_36.setReadOnly(True)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.u1_2.addWidget(self.lineEdit_36)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_37.setReadOnly(True)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.u1_2.addWidget(self.lineEdit_37)
        self.verticalLayout_40.addLayout(self.u1_2)
        self.u1_3 = QtWidgets.QHBoxLayout()
        self.u1_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.u1_3.setSpacing(6)
        self.u1_3.setObjectName("u1_3")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_38.setReadOnly(True)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.u1_3.addWidget(self.lineEdit_38)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_39.setReadOnly(True)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.u1_3.addWidget(self.lineEdit_39)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_40.setReadOnly(True)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.u1_3.addWidget(self.lineEdit_40)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_41.setReadOnly(True)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.u1_3.addWidget(self.lineEdit_41)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_42.setReadOnly(True)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.u1_3.addWidget(self.lineEdit_42)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_43.setReadOnly(True)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.u1_3.addWidget(self.lineEdit_43)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_44.setReadOnly(True)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.u1_3.addWidget(self.lineEdit_44)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_45.setReadOnly(True)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.u1_3.addWidget(self.lineEdit_45)
        self.verticalLayout_40.addLayout(self.u1_3)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_ult_data)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 56, 81))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_46 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_46.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.label = QtWidgets.QLabel(self.layoutWidget4)
        self.label.setObjectName("label")
        self.verticalLayout_46.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_46.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_46.addWidget(self.label_3)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_ult_data)
        self.layoutWidget5.setGeometry(QtCore.QRect(60, 10, 731, 16))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_11.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_11.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_11.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_11.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_11.addWidget(self.label_25)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.pushButton_4.raise_()
        self.groupBox_gyro_data.raise_()
        self.groupBox_ult_check.raise_()
        self.verticalLayoutWidget.raise_()
        self.layoutWidget_2.raise_()
        self.groupBox_ult_data.raise_()
        self.tabWidget_all.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_89 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_89.setGeometry(QtCore.QRect(170, 120, 85, 20))
        self.lineEdit_89.setReadOnly(True)
        self.lineEdit_89.setObjectName("lineEdit_89")
        self.label_60 = QtWidgets.QLabel(self.tab_2)
        self.label_60.setGeometry(QtCore.QRect(100, 120, 54, 12))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.tab_2)
        self.label_61.setGeometry(QtCore.QRect(100, 160, 54, 12))
        self.label_61.setObjectName("label_61")
        self.lineEdit_90 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_90.setGeometry(QtCore.QRect(170, 160, 85, 20))
        self.lineEdit_90.setReadOnly(True)
        self.lineEdit_90.setObjectName("lineEdit_90")
        self.label_62 = QtWidgets.QLabel(self.tab_2)
        self.label_62.setGeometry(QtCore.QRect(100, 200, 54, 12))
        self.label_62.setObjectName("label_62")
        self.lineEdit_91 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_91.setGeometry(QtCore.QRect(170, 200, 85, 20))
        self.lineEdit_91.setReadOnly(True)
        self.lineEdit_91.setObjectName("lineEdit_91")
        self.label_63 = QtWidgets.QLabel(self.tab_2)
        self.label_63.setGeometry(QtCore.QRect(330, 140, 81, 21))
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.tab_2)
        self.label_64.setGeometry(QtCore.QRect(330, 190, 81, 21))
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.tab_2)
        self.label_65.setGeometry(QtCore.QRect(330, 170, 71, 16))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.tab_2)
        self.label_66.setGeometry(QtCore.QRect(330, 120, 71, 16))
        self.label_66.setObjectName("label_66")
        self.tabWidget_all.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_16.addLayout(self.verticalLayout_2)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.checkBox_19 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_19.setObjectName("checkBox_19")
        self.verticalLayout_32.addWidget(self.checkBox_19)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_102 = QtWidgets.QLabel(self.groupBox_4)
        self.label_102.setObjectName("label_102")
        self.verticalLayout_3.addWidget(self.label_102)
        self.label_103 = QtWidgets.QLabel(self.groupBox_4)
        self.label_103.setObjectName("label_103")
        self.verticalLayout_3.addWidget(self.label_103)
        self.label_104 = QtWidgets.QLabel(self.groupBox_4)
        self.label_104.setObjectName("label_104")
        self.verticalLayout_3.addWidget(self.label_104)
        self.label_105 = QtWidgets.QLabel(self.groupBox_4)
        self.label_105.setObjectName("label_105")
        self.verticalLayout_3.addWidget(self.label_105)
        self.verticalLayout_35.addLayout(self.verticalLayout_3)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_35.addWidget(self.pushButton_22)
        self.verticalLayout_32.addWidget(self.groupBox_4)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_34.setSpacing(1)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_128 = QtWidgets.QLabel(self.groupBox_9)
        self.label_128.setObjectName("label_128")
        self.verticalLayout_34.addWidget(self.label_128)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_34.addWidget(self.lineEdit_10)
        self.label_129 = QtWidgets.QLabel(self.groupBox_9)
        self.label_129.setObjectName("label_129")
        self.verticalLayout_34.addWidget(self.label_129)
        self.lineEdit_100 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_100.setObjectName("lineEdit_100")
        self.verticalLayout_34.addWidget(self.lineEdit_100)
        self.label_130 = QtWidgets.QLabel(self.groupBox_9)
        self.label_130.setObjectName("label_130")
        self.verticalLayout_34.addWidget(self.label_130)
        self.lineEdit_102 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_102.setObjectName("lineEdit_102")
        self.verticalLayout_34.addWidget(self.lineEdit_102)
        self.label_131 = QtWidgets.QLabel(self.groupBox_9)
        self.label_131.setObjectName("label_131")
        self.verticalLayout_34.addWidget(self.label_131)
        self.lineEdit_101 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_101.setObjectName("lineEdit_101")
        self.verticalLayout_34.addWidget(self.lineEdit_101)
        self.label_132 = QtWidgets.QLabel(self.groupBox_9)
        self.label_132.setObjectName("label_132")
        self.verticalLayout_34.addWidget(self.label_132)
        self.lineEdit_103 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_103.setEnabled(False)
        self.lineEdit_103.setObjectName("lineEdit_103")
        self.verticalLayout_34.addWidget(self.lineEdit_103)
        self.label_133 = QtWidgets.QLabel(self.groupBox_9)
        self.label_133.setObjectName("label_133")
        self.verticalLayout_34.addWidget(self.label_133)
        self.lineEdit_104 = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_104.setEnabled(False)
        self.lineEdit_104.setObjectName("lineEdit_104")
        self.verticalLayout_34.addWidget(self.lineEdit_104)
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_25.sizePolicy().hasHeightForWidth())
        self.pushButton_25.setSizePolicy(sizePolicy)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_34.addWidget(self.pushButton_25)
        self.verticalLayout_34.setStretch(0, 1)
        self.verticalLayout_34.setStretch(1, 1)
        self.verticalLayout_34.setStretch(2, 1)
        self.verticalLayout_34.setStretch(3, 1)
        self.verticalLayout_34.setStretch(4, 1)
        self.verticalLayout_34.setStretch(5, 1)
        self.verticalLayout_34.setStretch(6, 1)
        self.verticalLayout_34.setStretch(7, 1)
        self.verticalLayout_34.setStretch(8, 1)
        self.verticalLayout_34.setStretch(9, 1)
        self.verticalLayout_34.setStretch(10, 1)
        self.verticalLayout_34.setStretch(11, 1)
        self.verticalLayout_34.setStretch(12, 2)
        self.verticalLayout_32.addWidget(self.groupBox_9)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_3.setObjectName("comboBox_3")
        self.verticalLayout_33.addWidget(self.comboBox_3)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_33.addWidget(self.pushButton_18)
        self.verticalLayout_32.addWidget(self.groupBox_6)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_59 = QtWidgets.QLabel(self.tab_4)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_14.addWidget(self.label_59)
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_14.addWidget(self.label_19)
        self.verticalLayout_31.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_58 = QtWidgets.QLabel(self.tab_4)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_15.addWidget(self.label_58)
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.verticalLayout_31.addLayout(self.horizontalLayout_15)
        self.verticalLayout_32.addLayout(self.verticalLayout_31)
        self.verticalLayout_32.setStretch(0, 1)
        self.verticalLayout_32.setStretch(1, 3)
        self.verticalLayout_32.setStretch(2, 5)
        self.verticalLayout_32.setStretch(3, 1)
        self.verticalLayout_32.setStretch(4, 1)
        self.horizontalLayout_16.addLayout(self.verticalLayout_32)
        self.horizontalLayout_16.setStretch(0, 6)
        self.horizontalLayout_16.setStretch(1, 1)
        self.tabWidget_all.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.layoutWidget6 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget6.setGeometry(QtCore.QRect(11, 490, 521, 42))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_69 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_28.addWidget(self.label_69)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget6)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_28.addWidget(self.progressBar)
        self.horizontalLayout_12.addLayout(self.verticalLayout_28)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 5)
        self.horizontalLayout_12.setStretch(2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setGeometry(QtCore.QRect(1, 11, 531, 471))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_12.setGeometry(QtCore.QRect(430, 430, 91, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_20.setGeometry(QtCore.QRect(260, 440, 95, 16))
        self.checkBox_20.setObjectName("checkBox_20")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_11.setGeometry(QtCore.QRect(14, 440, 211, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(50, 20, 301, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMaxVisibleItems(15)
        self.comboBox.setObjectName("comboBox")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_17.setGeometry(QtCore.QRect(430, 20, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(13, 420, 427, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_119 = QtWidgets.QLabel(self.groupBox_2)
        self.label_119.setGeometry(QtCore.QRect(10, 47, 360, 16))
        self.label_119.setObjectName("label_119")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 70, 401, 181))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(420, 70, 101, 181))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.checkBox_27 = QtWidgets.QCheckBox(self.layoutWidget7)
        self.checkBox_27.setChecked(True)
        self.checkBox_27.setObjectName("checkBox_27")
        self.verticalLayout_23.addWidget(self.checkBox_27)
        self.checkBox_26 = QtWidgets.QCheckBox(self.layoutWidget7)
        self.checkBox_26.setChecked(True)
        self.checkBox_26.setObjectName("checkBox_26")
        self.verticalLayout_23.addWidget(self.checkBox_26)
        self.checkBox_22 = QtWidgets.QCheckBox(self.layoutWidget7)
        self.checkBox_22.setChecked(True)
        self.checkBox_22.setObjectName("checkBox_22")
        self.verticalLayout_23.addWidget(self.checkBox_22)
        self.checkBox_28 = QtWidgets.QCheckBox(self.layoutWidget7)
        self.checkBox_28.setChecked(True)
        self.checkBox_28.setObjectName("checkBox_28")
        self.verticalLayout_23.addWidget(self.checkBox_28)
        self.checkBox_23 = QtWidgets.QCheckBox(self.layoutWidget7)
        self.checkBox_23.setChecked(True)
        self.checkBox_23.setObjectName("checkBox_23")
        self.verticalLayout_23.addWidget(self.checkBox_23)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 21, 41, 26))
        self.label_17.setWordWrap(True)
        self.label_17.setObjectName("label_17")
        self.layoutWidget8 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget8.setGeometry(QtCore.QRect(13, 370, 261, 42))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_38.addWidget(self.label_15)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setAcceptDrops(False)
        self.dateTimeEdit.setTime(QtCore.QTime(0, 0, 0))
        self.dateTimeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateTimeEdit.setCalendarPopup(True)
        self.dateTimeEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout_38.addWidget(self.dateTimeEdit)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 260, 441, 101))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_120 = QtWidgets.QLabel(self.groupBox_2)
        self.label_120.setGeometry(QtCore.QRect(460, 280, 61, 20))
        self.label_120.setObjectName("label_120")
        self.lineEdit_105 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_105.setGeometry(QtCore.QRect(460, 340, 61, 20))
        self.lineEdit_105.setObjectName("lineEdit_105")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(460, 320, 54, 12))
        self.label_18.setObjectName("label_18")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 540, 521, 61))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_93 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_93.setGeometry(QtCore.QRect(280, 30, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_93.setFont(font)
        self.lineEdit_93.setObjectName("lineEdit_93")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_21.setGeometry(QtCore.QRect(230, 40, 41, 21))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_20.setGeometry(QtCore.QRect(230, 20, 41, 21))
        self.pushButton_20.setObjectName("pushButton_20")
        self.lineEdit_92 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_92.setGeometry(QtCore.QRect(20, 30, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_92.setFont(font)
        self.lineEdit_92.setObjectName("lineEdit_92")
        self.label_67 = QtWidgets.QLabel(self.groupBox_3)
        self.label_67.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.groupBox_3)
        self.label_68.setGeometry(QtCore.QRect(280, 10, 131, 16))
        self.label_68.setObjectName("label_68")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_19.setGeometry(QtCore.QRect(779, 580, 121, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_57 = QtWidgets.QLabel(self.tab_3)
        self.label_57.setGeometry(QtCore.QRect(540, 10, 78, 16))
        self.label_57.setObjectName("label_57")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(541, 29, 361, 551))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.tabWidget_all.addTab(self.tab_3, "")
        self.groupBox.raise_()
        self.tabWidget_all.raise_()
        self.layoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1203, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.tabWidget_all.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_101.setText(_translate("MainWindow", "TOF"))
        self.label_97.setText(_translate("MainWindow", "2"))
        self.label_90.setText(_translate("MainWindow", "超声8"))
        self.label_92.setText(_translate("MainWindow", "2"))
        self.label_82.setText(_translate("MainWindow", "超声7"))
        self.label_83.setText(_translate("MainWindow", "2"))
        self.label_85.setText(_translate("MainWindow", "超声6"))
        self.label_84.setText(_translate("MainWindow", "2"))
        self.label_80.setText(_translate("MainWindow", "超声5"))
        self.label_81.setText(_translate("MainWindow", "2"))
        self.label_78.setText(_translate("MainWindow", "超声4"))
        self.label_79.setText(_translate("MainWindow", "2"))
        self.label_76.setText(_translate("MainWindow", "超声3"))
        self.label_77.setText(_translate("MainWindow", "2"))
        self.label_73.setText(_translate("MainWindow", "超声2"))
        self.label_72.setText(_translate("MainWindow", "2"))
        self.label_74.setText(_translate("MainWindow", "超声1"))
        self.label_75.setText(_translate("MainWindow", "2"))
        self.label_95.setText(_translate("MainWindow", "红外6"))
        self.label_94.setText(_translate("MainWindow", "2"))
        self.label_96.setText(_translate("MainWindow", "红外5"))
        self.label_98.setText(_translate("MainWindow", "2"))
        self.label_89.setText(_translate("MainWindow", "红外4"))
        self.label_88.setText(_translate("MainWindow", "2"))
        self.label_91.setText(_translate("MainWindow", "红外3"))
        self.label_99.setText(_translate("MainWindow", "2"))
        self.label_87.setText(_translate("MainWindow", "红外2"))
        self.label_86.setText(_translate("MainWindow", "2"))
        self.label_93.setText(_translate("MainWindow", "红外1"))
        self.label_100.setText(_translate("MainWindow", "2"))
        self.label_116.setText(_translate("MainWindow", "以下传感器在机器人背后"))
        self.label_110.setText(_translate("MainWindow", "回充红外左"))
        self.label_111.setText(_translate("MainWindow", "2"))
        self.label_113.setText(_translate("MainWindow", "回充红外右"))
        self.label_112.setText(_translate("MainWindow", "2"))
        self.label_115.setText(_translate("MainWindow", "地检红外"))
        self.label_114.setText(_translate("MainWindow", "2"))
        self.groupBox.setTitle(_translate("MainWindow", "设备连接设置"))
        self.label_71.setText(_translate("MainWindow", "机器型号："))
        self.label_117.setText(_translate("MainWindow", "当前导航节点："))
        self.label_118.setText(_translate("MainWindow", "："))
        self.label_42.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_open_close.setText(_translate("MainWindow", "连接传感器"))
        self.groupBox_ult_check.setTitle(_translate("MainWindow", "超声波选项卡"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_3.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_4.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_5.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_6.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_7.setText(_translate("MainWindow", "CheckBox"))
        self.checkBox_8.setText(_translate("MainWindow", "CheckBox"))
        self.groupBox_gyro_data.setTitle(_translate("MainWindow", "陀螺仪"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_13.setText(_translate("MainWindow", "PushButton"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_47.setText(_translate("MainWindow", "TextLabel"))
        self.label_48.setText(_translate("MainWindow", "TextLabel"))
        self.label_49.setText(_translate("MainWindow", "TextLabel"))
        self.label_50.setText(_translate("MainWindow", "TextLabel"))
        self.label_51.setText(_translate("MainWindow", "TextLabel"))
        self.label_52.setText(_translate("MainWindow", "TextLabel"))
        self.label_53.setText(_translate("MainWindow", "TextLabel"))
        self.label_55.setText(_translate("MainWindow", "TextLabel"))
        self.label_54.setText(_translate("MainWindow", "TextLabel"))
        self.checkBox_15.setText(_translate("MainWindow", "是否后台记录数据"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "超声波"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "墙检红外"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", "头部TOF红外"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "回充红外"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "地检红外"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.label_43.setText(_translate("MainWindow", "采样次数："))
        self.label_44.setText(_translate("MainWindow", "0"))
        self.label_45.setText(_translate("MainWindow", "采样频率Hz："))
        self.label_46.setText(_translate("MainWindow", "0"))
        self.groupBox_ult_data.setTitle(_translate("MainWindow", "超声波（cm）"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_21.setText(_translate("MainWindow", "TextLabel"))
        self.label_22.setText(_translate("MainWindow", "TextLabel"))
        self.label_23.setText(_translate("MainWindow", "TextLabel"))
        self.label_24.setText(_translate("MainWindow", "TextLabel"))
        self.label_25.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab), _translate("MainWindow", "传感器数据"))
        self.label_60.setText(_translate("MainWindow", "电压mV："))
        self.label_61.setText(_translate("MainWindow", "电量%："))
        self.label_62.setText(_translate("MainWindow", "温度℃:"))
        self.label_63.setText(_translate("MainWindow", "0"))
        self.label_64.setText(_translate("MainWindow", "0"))
        self.label_65.setText(_translate("MainWindow", "采样频率Hz："))
        self.label_66.setText(_translate("MainWindow", "采样次数："))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_2), _translate("MainWindow", "电池(预留）"))
        self.checkBox_19.setText(_translate("MainWindow", "是否后台记录数据"))
        self.groupBox_4.setTitle(_translate("MainWindow", "选中点参数"))
        self.label_102.setText(_translate("MainWindow", "长度（m）："))
        self.label_103.setText(_translate("MainWindow", "TextLabel"))
        self.label_104.setText(_translate("MainWindow", "角度（°）："))
        self.label_105.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_22.setText(_translate("MainWindow", "清除显示"))
        self.groupBox_9.setTitle(_translate("MainWindow", "误报测试"))
        self.label_128.setText(_translate("MainWindow", "距离（m）："))
        self.lineEdit_10.setText(_translate("MainWindow", "1"))
        self.label_129.setText(_translate("MainWindow", "时间（min）："))
        self.lineEdit_100.setText(_translate("MainWindow", "30"))
        self.label_130.setText(_translate("MainWindow", "起始角度："))
        self.lineEdit_102.setText(_translate("MainWindow", "0"))
        self.label_131.setText(_translate("MainWindow", "终止角度："))
        self.lineEdit_101.setText(_translate("MainWindow", "180"))
        self.label_132.setText(_translate("MainWindow", "误报次数："))
        self.label_133.setText(_translate("MainWindow", "误报百分比："))
        self.pushButton_25.setText(_translate("MainWindow", "开始"))
        self.pushButton_18.setText(_translate("MainWindow", "PushButton"))
        self.label_59.setText(_translate("MainWindow", "采样次数："))
        self.label_19.setText(_translate("MainWindow", "0"))
        self.label_58.setText(_translate("MainWindow", "采样频率Hz："))
        self.label_20.setText(_translate("MainWindow", "0"))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_4), _translate("MainWindow", "单线雷达"))
        self.label_69.setText(_translate("MainWindow", "                 文件下载中，请稍后..."))
        self.groupBox_2.setTitle(_translate("MainWindow", "日志选项"))
        self.pushButton_12.setText(_translate("MainWindow", "下载"))
        self.checkBox_20.setText(_translate("MainWindow", "所有时间日志"))
        self.pushButton_17.setText(_translate("MainWindow", "刷新列表"))
        self.label_16.setText(_translate("MainWindow", "日志往前时间范围min： eg：30代表分钟 2-10-30代表2天10小时30分钟:"))
        self.label_119.setText(_translate("MainWindow", "手动bag包列表（Cruzr1S ROS2.41版本及以上支持），请勾选下载："))
        self.checkBox_27.setText(_translate("MainWindow", "导航日志"))
        self.checkBox_26.setText(_translate("MainWindow", "ROS日志"))
        self.checkBox_22.setText(_translate("MainWindow", "导航地图"))
        self.checkBox_28.setText(_translate("MainWindow", "手动bag包"))
        self.checkBox_23.setText(_translate("MainWindow", "自动bag包"))
        self.label_17.setText(_translate("MainWindow", "地图："))
        self.label_15.setText(_translate("MainWindow", "需要导出日志时间:"))
        self.dateTimeEdit.setDisplayFormat(_translate("MainWindow", "yyyy-M-d H:mm"))
        self.label_120.setText(_translate("MainWindow", "<-bug描述"))
        self.lineEdit_105.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "bug号:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "时间转换"))
        self.pushButton_21.setText(_translate("MainWindow", "<<"))
        self.pushButton_20.setText(_translate("MainWindow", ">>"))
        self.label_67.setText(_translate("MainWindow", "时间戳:"))
        self.label_68.setText(_translate("MainWindow", "标准时间:"))
        self.pushButton_19.setText(_translate("MainWindow", "清除列表显示"))
        self.label_57.setText(_translate("MainWindow", "日志输出状态:"))
        self.tabWidget_all.setTabText(self.tabWidget_all.indexOf(self.tab_3), _translate("MainWindow", "ROS日志"))

import c1s_rc
